module HaskellNix.Update.Cohort.Freeze (
    parseCohortFreeze,
    normaliseCabalFreeze,
    renderCohortFreeze,
    FreezeHeader (..),
) where

import Control.Monad (foldM)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as Text
import Distribution.Pretty (prettyShow)
import Distribution.Version (Version)
import HaskellNix.Update.Cohort.Inventory (projectFields)
import HaskellNix.Update.Cohort.Model (parseVersion)

data FreezeHeader = FreezeHeader
    {indexState :: !Text, compiler :: !Text, haskellNixRevision :: !Text, command :: !Text}
    deriving stock (Eq, Show)

-- Reject malformed/version-range constraints instead of accepting partial data.
-- Cabal's flag assignments are the only constraint records deliberately dropped.
normaliseCabalFreeze :: Text -> Either Text (Map Text Version)
normaliseCabalFreeze input = foldM insert Map.empty entries
  where
    entries = [Text.strip item | ("constraints", value) <- projectFields input, item <- Text.splitOn "," value, not (Text.null (Text.strip item))]
    insert result entry = case Text.words entry of
        [name, equality] | Just version <- Text.stripPrefix "==" equality -> add result name version
        [name, "==", version] -> add result name version
        _ : flags | not (null flags) && all (\flag -> Text.isPrefixOf "+" flag || Text.isPrefixOf "-" flag) flags -> Right result
        _ -> Left ("invalid freeze constraint: " <> entry)
    add result qualifiedName rawVersion = do
        version <- parseVersion rawVersion
        let name = maybe qualifiedName id (Text.stripPrefix "any." qualifiedName)
        case Map.lookup name result of
            Just old | old /= version -> Left ("conflicting freeze versions for " <> name)
            _ -> Right (Map.insert name version result)

parseCohortFreeze :: Text -> Either Text (Map Text Version)
parseCohortFreeze input = do
    case [value | ("index-state", value) <- projectFields input] of
        [_] -> pure ()
        _ -> Left "cohort freeze must contain exactly one index-state"
    normaliseCabalFreeze input

renderCohortFreeze :: FreezeHeader -> Map Text Version -> Text
renderCohortFreeze FreezeHeader{indexState, compiler, haskellNixRevision, command} versions =
    Text.unlines
        ( [ "-- Generated by " <> command <> ". Do not edit."
          , "-- Compiler: " <> compiler
          , "-- haskell-nix: " <> haskellNixRevision
          , "index-state: hackage.haskell.org " <> indexState
          , "constraints:"
          ]
            <> zipWith (\prefix (name, version) -> prefix <> "any." <> name <> " ==" <> Text.pack (prettyShow version)) ("  " : repeat "  , ") (Map.toAscList versions)
        )
